### ISSUE TITLE
The code is outdated

### ISSUE THREAD

**Issue by ixanezis** [KevinBusse/cg-referee-mean-max#1]
While trying to run the code some issues arise.
One example of them is that `handleInitInputForReferee` is called with argument `playerCount = 2`, although different parts of code assume it is equal to 3.
Also, the `nextPlayer` function immediatelly sets `newRound = false`, making a NullPointerException in the very beginning of the simulation.

**Comment by Emerion** [comment]
I created a pull-request with the changes I've made earlier today to resolve this problem.
Not entirely sure if results are reliable but for first testing it seemed to work.

**Comment by kevinsandow** [comment]
This was solved by: #2
